server:
  port: 8762
spring:
  application:
    name: lagou-cloud-eureka-server
# eureka客户端配置， Eureka Server也是一个client
eureka:
  instance:
    hostname: LagouCloudEurekaServerB
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:1.0-SNAPSHOT
  client:
    service-url: #配置客户端所交互的Eureka Server的地址
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka
    register-with-eureka: true # 当前自己就是Server，不需要注册自己
    fetch-registry: true #获取注册中心的服务信息，自己就是Server，不需要从Eureka Server获取信息


