server:
  port: 8091
spring:
  application:
    name: lagou-service-autodeliver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.224.134.91:3306/lagou?useUnicode=true&characterEncoding=utf8
    username: root
    password: mysqlpass
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #避免将驼峰命名转换为下划线命名
eureka:
  client:
    service-url: #配置客户端所交互的Eureka Server的地址
      # 集群模式下，应该指向其他Eureka Server；多个Server用逗号“，”隔开
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka,http://LagouCloudEurekaServerB:8762/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:1.0-SNAPSHOT

# springboot中暴露健康检查等断点接⼝
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # 暴露健康接⼝的细节
  endpoint:
    health:
      show-details: always

# 对指定的微服务负载均衡，不加的话就是全局负载均衡
lagou-service-resume:
  ribbon:
    ConnectTimeout: 2000 #请求连接超时时间
    ReadTimeout: 2000 # Feign请求处理超时时间
    OkToRetryOnAllOperations: true #对所有操作都进⾏重试
    ####根据如上配置，当访问到故障请求的时候，它会再尝试访问⼀次当前实例（次数由MaxAutoRetries配置），
    ####如果不⾏，就换⼀个实例进⾏访问，如果还不⾏，再换⼀次实例访问（更换次数由MaxAutoRetriesNextServer配置），
    ####如果依然不⾏，返回失败信息。
    MaxAutoRetries: 0 #对当前选中实例重试次数，不包括第⼀次调⽤
    MaxAutoRetriesNextServer: 0 #切换实例的重试次数
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #负载策略调整

logging:
  level:
    com.lagou.edu.service.ResumeFeignClient: debug

# 开启Feign的熔断功能
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #Hystrix的超时时⻓设置