server:
  port: 8761
spring:
  application:
    name: lagou-cloud-eureka-server
# eureka客户端配置， Eureka Server也是一个client
eureka:
  instance:
    hostname: LagouCloudEurekaServerA
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
  client:
    service-url: #配置客户端所交互的Eureka Server的地址
      # 集群模式下，应该指向其他Eureka Server；多个Server用逗号“，”隔开
      defaultZone: http://LagouCloudEurekaServerB:8762/eureka
    register-with-eureka: true # 当前自己就是Server，不需要注册自己
    fetch-registry: true #获取注册中心的服务信息，自己就是Server，不需要从Eureka Server获取信息