server:
  port: 9006

eureka:
  client:
    service-url:
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka,http://LagouCloudEurekaServerB:8762/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@

spring:
  application:
    name: lagou-cloud-configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RickeyChen/lagou-config-repo.git
          username: rickeychen0390@outlook.com
          password: rickeyfair993257
#      label: master
  rabbitmq:
    host: 139.224.134.91
    port: 5672
    username: rickey
    password: rickey

# 暴露所有端口
management:
  endpoints:
    web:
      exposure:
        include: busrefresh